### ISSUE TITLE
newlines in text 

### ISSUE THREAD

**Issue by parisni** [marcschwartz/WriteXLS#13]
Hi,

Newlines looks not handled within text. AS a result for each newline in text, a new line in excel

**Comment by marcschwartz** [comment]
Hi,

This was reported about 6 months ago and there is not an easy resolution with WriteXLS. 

See issue 12:

https://github.com/marcschwartz/WriteXLS/issues/12

Thanks.

Marc

**Comment by parisni** [comment]
I Mark,

Thanks for the explanation. What about this workaround:
- add 2 arguments to WriteXLS:
    - NewlineColumns: vector
    - NewlineCharacter: strung ; default="<nl>"

Then before writing csv do : 
for each column in NewlineColumn
test if df$col contains NewlineCharacter ->Raise error "change Newline Character"
do gsub("\n", NewlineCharacter, df$col)
while parsing with perl do:
replace (NewlineCHaracter, "\n")

As a result you handle newlines that way

Thanks

**Comment by marcschwartz** [comment]
Hi Paris,

I appreciate the suggestions.

However, the approach you have above would still result in a single line, wide cell in the Excel worksheet. The embedded newline character is not recognized by default in Excel to split the text in the cell on multiple lines.

Thus, the use of replace() on the Perl side is not really needed once gsub() in R is used to add backslashes, so that the newline is not interpreted as a literal when written to the intermediate CSV file with write.table(). I showed an example of this in the prior issue.

To support in-cell text wrapping in Excel via Perl would require setting an additional format parameter in the Perl code for the target cell/worksheet. It would also begin to get into the slippery slope of then supporting other cell/worksheet formatting functionality in time (fonts, text and cell background colors, cell borders, other embedded characters, etc.), as I have had numerous other such requests over the years. 

As I have noted elsewhere, getting into cell formatting, beyond bolding the header row and setting column widths purely for readability, is beyond the scope of WriteXLS, which is designed just to facilitate the exporting of data frames to an Excel file for convenience, rather than a pure CSV file. I have been consistent in not going in the direction of adding lower level formatting control with the function.

For embedded newline characters, pre-formatting the data frame using gsub() before calling WriteXLS() is still an option for you, if you wish. Otherwise, there are other CRAN packages that support richer cell formatting functionality to enable lower level control when exporting to Excel files.

Regards,

Marc

**Comment by marcschwartz** [comment]
Hi Paris,

I wanted to let you know that version 6.0.0 of the WriteXLS package was just released. 

I was able to spend a fair amount of time recently, addressing this issue and related issues with embedded special character sequences. These are now better preserved in the Excel file that is generated and as an indirect consequence of the more robust handling, a multiline cell will be created where newlines are present.
