### ISSUE TITLE
apply AdjWidth after AutoFilter?

### ISSUE THREAD

**Issue by Courvoisier13** [marcschwartz/WriteXLS#14]
Hi,
is there a way to apply AdjWidth after AutoFilter? when AutoFilter is applied it takes away from the column name. readjusting in excel is possible. it would be nice if WriteXLS did that.

**Comment by marcschwartz** [comment]
Hi,

Thanks for your comments.

Unfortunately, there is no way to access the built-in auto-adjustment function in Excel for column widths via Perl. 

Thus, a kludge is used in the Perl scripts that are called from R, whereby the widest text (string width) in each column is obtained. Using Arial 10 as the presumptive font, the column width is estimated for widest text, and then extended by 10%. It is an imperfect way of doing this.

Thus, the width adjustment process in WriteXLS is independent of the auto-filter mechanism, which can be called directly via Perl. The behavior would not change whether the width is adjusted before or after the auto-filter is applied, since the column character widths themselves do not change.

The auto-width adjustment in Excel itself is more robust and sophisticated relative to how it works. It is unfortunate that there is not a way to access it via Perl.

**Comment by Courvoisier13** [comment]
Ah I see. Thank you for the detailed explanation.
