### ISSUE TITLE
Problem with missing Perl modules

### ISSUE THREAD

**Issue by briencj** [marcschwartz/WriteXLS#21]
Hi Marc,

I have installed the latest version of Strawberry Pearl (see PearlVersion.jpg), but when I run testPerl in R it is reported that two mandatory Perl modules are missing (see testPerl.jpg). I have used cpanm to check that they are installed, but no luck in making them available. Can you offer any suggestions. 

Cheers ,

Chris Brien
chris.brien@adelaide.edu.au

![PerlVersion](https://user-images.githubusercontent.com/12837653/154601932-87e8df4a-2bf4-45d7-800f-8124150a197e.jpg)
![testPerl](https://user-images.githubusercontent.com/12837653/154601934-9e2088ee-51a9-4ee1-b37f-070a62af0988.jpg)

**Comment by marcschwartz** [comment]
Hi Chris,

Thanks for your post.

Unfortunately, I am traveling at the moment, so have limited access to any resources.

From what I can tell on the Strawberry Perl web site for the version that you have installed, GetOpt::Long is part of their distribution, but I am not seeing File::Basename there, unless they bundle it with another package:

https://strawberryperl.com/release-notes/5.32.1.1-64bit.html

It sounds like there may be a path issue with your Perl installation, such that the location where those modules are installed is not in the Windows search path, thus they are not being found.

You might try running testPerl(verbose =  TRUE), to see if the additional output offers any insights into what paths are being searched, versus where the Perl modules are installed.

I am not clear whether this issue is an indication of a corrupt Perl installation, or something else is going on. You might also try re-installing Strawberry Perl to see if that helps. If not, you might try to contact them for some assistance with their distribution.

I am not on Windows, but when I was years ago, I tended to use the ActiveState Perl distribution, which I reference in the WriteXLS documentation and found easier to install and maintain. That might be another option for you. 

I hope that the above may be helpful, or that the Strawberry Perl folks can offer some insights given the information that you can provide, since this is not strictly an R issue per se.

Please provide an update if you make any progress.

**Comment by briencj** [comment]
Hi Marc,

Thanks for your response. I have now found the problem.

I checked that all the modules are available in Strawberry Perl and they are in C:\Strawberry\perls\lib. 

However, I ran Perl.Path <- system.file("Perl", package = "WriteXLS") out of testPerl and found that it  returns "C:\\rtools40\\usr\\bin\\perl.exe", because I have rtools4 installed to build packages under Windows. 

However, the problem turned out to be that rtools4 was on the Windows path ahead of Strawberry Perl. Moving Strawberry Perl ahead of rtools4 on the Windows path fixed the problem.

Can I suggest that when verbose = TRUE, that Perl.Path is printed out so that you can see what installation of perl is being found. It is not uncommon to have multiple version on a computer because some come packaged with other software.

I anticipate that your package is going to be very useful and I am looking forward to using it. Thanks for producing it.

Cheers, Chris

**Comment by marcschwartz** [comment]
Hi Chris,

Thanks for the updates and glad that you were able to resolve the issue. I had not considered that you had a second Perl installation.

I have made a note of your suggestion, and will look to include that in a future update.

I hope that you find the package useful.

Regards,

Marc
