### ISSUE TITLE
Does not work on Perl >= 5.20 because of double decoding

### ISSUE THREAD

**Issue by brujeria** [marcschwartz/WriteXLS#6]
Looks like there is a breaking change in Perl 5.20, example

```
> library(WriteXLS)
> test <- data.frame(foo='čebula')
> WriteXLS('test', Encoding="UTF-8", verbose=1)

Cannot decode string with wide characters at /usr/lib64/perl5/5.20.2/x86_64-linux-thread-multi/Encode.pm line 215, <CSVFILE> line 3.
 at /usr/lib64/perl5/5.20.2/x86_64-linux-thread-multi/Encode.pm line 215, <CSVFILE> line 3.
	Encode::decode_utf8("\x{10d}ebula") called at /usr/lib64/R/library/WriteXLS/Perl/WriteXLS.pl line 295
```

Proposed patch:

```diff
diff --git a/inst/Perl/WriteXLS.pl b/inst/Perl/WriteXLS.pl
index 7164b78..89924c3 100755
--- a/inst/Perl/WriteXLS.pl
+++ b/inst/Perl/WriteXLS.pl
@@ -38,8 +38,16 @@ use File::Basename;
 use Text::CSV_PP;
 use Encode;
 
-
-
+# double decoding safety measure (breaking change in perl 5.20)
+sub safe_decode_utf8 ($) {
+    my $octets = shift;
+    if (!Encode::is_utf8($octets)) {
+        return decode_utf8($octets);
+    }
+    else {
+        return $octets;
+    }
+}
 
 ###############################################################################
 # Initialize and get command line arguments
@@ -277,7 +285,7 @@ foreach my $FileName (@FileNames) {
             $Fld = substr $Fld, 18;
             if ($Fld ne "") {
               if ($Encoding eq "UTF-8") {
-                $WorkSheet->write_comment(0, $Column, decode_utf8($Fld));
+                $WorkSheet->write_comment(0, $Column, safe_decode_utf8($Fld));
              } else {
                 $WorkSheet->write_comment(0, $Column, decode("iso-8859-1", $Fld));
               }
@@ -291,7 +299,7 @@ foreach my $FileName (@FileNames) {
       if ($CommentRow != 1) {
         foreach my $Fld (@Fields) {
           if ($Encoding eq "UTF-8") {
-            $WorkSheet->write($Row, $Column, decode_utf8($Fld));
+            $WorkSheet->write($Row, $Column, safe_decode_utf8($Fld));
           } else {
             $WorkSheet->write($Row, $Column, decode("iso-8859-1", $Fld));
          }

**Comment by marcschwartz** [comment]
Hi,

Thanks for reporting this issue and proposing a patch.

Due to my current workload, it will likely be at least a week before I can look at this and test the proposed patch for both Perl script files (XLS and XLSX).

I will update the repo here and release a new version to CRAN as soon as I can.

Thanks again and regards,

Marc

**Comment by brujeria** [comment]
Thanks. I've attached a more complete patch which fixes both XLS and XLSX scripts. It works on Perl 5.20, should also work on 5.18 and lower, but I haven't tested it yet.

-a

**Comment by marcschwartz** [comment]
Hi,

Apologies that it has taken longer than I planned to address this issue. Between work and another encoding related issue reported to me by e-mail, this turned out to be a more nuanced issue than I anticipated.

After engaging in a lot of research dealing with encoding in Perl and ultimately contacting John McNamara, who wrote the Excel related modules that I use, I had to rewrite the encoding related code in both Perl scripts.

Thus, I have a new version of the package for testing and would like to make it available to you before updating CRAN. 

I have uploaded a source tarball of the package here, as it appears that you are on Linux:

  https://www.dropbox.com/s/m70hf3sq4j07iaf/WriteXLS_3.6.0.tar.gz?dl=0

If you could do some testing with it to see if you can still replicate the issue you reported, that would be appreciated. 

Let me know what you find.

Thanks,

Marc

**Comment by brujeria** [comment]
Yes, it works for our purposes (using Unicode and Perl 5.20).

Thanks again,

Aleksander

**Comment by marcschwartz** [comment]
Great! Thanks for the confirmation!

I will be submitting an updated version to CRAN.

Closing this issue.
